import http from 'k6/http';
import { check, sleep, group } from 'k6';

export const options = {
  vus: 5,
  duration: '1m',
  thresholds: {
    http_req_duration: ['p(95)<800'],
    http_req_failed: ['rate<0.05'],
  },
};

const fastapiBase = __ENV.FASTAPI_BASE_URL || 'http://app:8000';
const nodeBase = __ENV.NODE_BASE_URL || 'http://node-api:3001';
const springBase = __ENV.SPRING_BASE_URL || 'http://spring-api:8080';

function jsonHeaders() {
  return { headers: { 'Content-Type': 'application/json' } };
}

export default function () {
  const suffix = Math.floor(Math.random() * 1e6);

  group('list all services', () => {
    [
      `${fastapiBase}/api/v1/todos/`,
      `${nodeBase}/api/v1/todos`,
      `${springBase}/api/v1/todos`,
    ].forEach((url) => {
      const res = http.get(url);
      check(res, { 'GET 200': (r) => r.status === 200 });
    });
  });

  let todoId;

  group('create via FastAPI', () => {
    const res = http.post(
      `${fastapiBase}/api/v1/todos/`,
      JSON.stringify({
        title: `k6 load ${suffix}`,
        description: 'generated by k6',
        completed: false,
      }),
      jsonHeaders(),
    );
    check(res, { 'create 201': (r) => r.status === 201 });
    if (res.status === 201) {
      todoId = res.json('id');
    }
  });

  if (todoId) {
    group('read via Node & Spring', () => {
      const nodeRes = http.get(`${nodeBase}/api/v1/todos/${todoId}`);
      const springRes = http.get(`${springBase}/api/v1/todos/${todoId}`);
      check(nodeRes, { 'node GET 200': (r) => r.status === 200 });
      check(springRes, { 'spring GET 200': (r) => r.status === 200 });
    });

    group('update via Node', () => {
      const res = http.put(
        `${nodeBase}/api/v1/todos/${todoId}`,
        JSON.stringify({ title: `k6 updated ${suffix}`, completed: true }),
        jsonHeaders(),
      );
      check(res, { 'node PUT 200': (r) => r.status === 200 });
    });

    group('delete via Spring', () => {
      const res = http.del(`${springBase}/api/v1/todos/${todoId}`);
      check(res, { 'spring DELETE 204': (r) => r.status === 204 });
    });
  }

  sleep(1);
}
