import http from 'k6/http';
import { check, sleep, group } from 'k6';

export const options = {
  vus: 5,
  duration: '1m',
  thresholds: {
    http_req_duration: ['p(95)<800'],
    http_req_failed: ['rate<0.05'],
  },
};

const fastapiBase = __ENV.FASTAPI_BASE_URL || 'http://app:8000';
const nodeBase = __ENV.NODE_BASE_URL || 'http://node-api:3001';
const springBase = __ENV.SPRING_BASE_URL || 'http://spring-api:8080';
const goBase = __ENV.GO_BASE_URL || 'http://go-api:3002';
const rustBase = __ENV.RUST_BASE_URL || 'http://rust-api:3003';

function jsonHeaders() {
  return { headers: { 'Content-Type': 'application/json' } };
}

export default function () {
  const suffix = Math.floor(Math.random() * 1e6);

  group('list all services', () => {
    [
      `${fastapiBase}/api/v1/todos/`,
      `${nodeBase}/api/v1/todos`,
      `${springBase}/api/v1/todos`,
      `${goBase}/api/v1/todos`,
      `${rustBase}/api/v1/todos`,
    ].forEach((url) => {
      const res = http.get(url);
      check(res, { 'GET 200': (r) => r.status === 200 });
    });
  });

  let todoId;
  let goTodoId;
  let rustTodoId;

  group('create via FastAPI', () => {
    const res = http.post(
      `${fastapiBase}/api/v1/todos/`,
      JSON.stringify({
        title: `k6 load ${suffix}`,
        description: 'generated by k6',
        completed: false,
      }),
      jsonHeaders(),
    );
    check(res, { 'create 201': (r) => r.status === 201 });
    if (res.status === 201) {
      todoId = res.json('id');
    }
  });

  if (todoId) {
    group('read via Node & Spring', () => {
      const nodeRes = http.get(`${nodeBase}/api/v1/todos/${todoId}`);
      const springRes = http.get(`${springBase}/api/v1/todos/${todoId}`);
      check(nodeRes, { 'node GET 200': (r) => r.status === 200 });
      check(springRes, { 'spring GET 200': (r) => r.status === 200 });
    });

    group('update via Node', () => {
      const res = http.put(
        `${nodeBase}/api/v1/todos/${todoId}`,
        JSON.stringify({ title: `k6 updated ${suffix}`, completed: true }),
        jsonHeaders(),
      );
      check(res, { 'node PUT 200': (r) => r.status === 200 });
    });

    group('delete via Spring', () => {
      const res = http.del(`${springBase}/api/v1/todos/${todoId}`);
      check(res, { 'spring DELETE 204': (r) => r.status === 204 });
    });
  }

  group('create via Go', () => {
    const res = http.post(
      `${goBase}/api/v1/todos`,
      JSON.stringify({
        title: `k6 go load ${suffix}`,
        description: 'generated by k6 via go',
        completed: false,
      }),
      jsonHeaders(),
    );
    check(res, { 'go create 201': (r) => r.status === 201 });
    if (res.status === 201) {
      goTodoId = res.json('id');
    }
  });

  if (goTodoId) {
    group('read via FastAPI & Node', () => {
      const fastapiRes = http.get(`${fastapiBase}/api/v1/todos/${goTodoId}`);
      const nodeRes = http.get(`${nodeBase}/api/v1/todos/${goTodoId}`);
      check(fastapiRes, { 'fastapi GET 200': (r) => r.status === 200 });
      check(nodeRes, { 'node GET 200 (go todo)': (r) => r.status === 200 });
    });

    group('update via Go', () => {
      const res = http.put(
        `${goBase}/api/v1/todos/${goTodoId}`,
        JSON.stringify({ title: `k6 go updated ${suffix}`, completed: true }),
        jsonHeaders(),
      );
      check(res, { 'go PUT 200': (r) => r.status === 200 });
    });

    group('delete via FastAPI', () => {
      const res = http.del(`${fastapiBase}/api/v1/todos/${goTodoId}`);
      check(res, { 'fastapi DELETE 204': (r) => r.status === 204 });
    });
  }

  group('create via Rust', () => {
    const res = http.post(
      `${rustBase}/api/v1/todos`,
      JSON.stringify({
        title: `k6 rust load ${suffix}`,
        description: 'generated by k6 via rust',
        completed: false,
      }),
      jsonHeaders(),
    );
    check(res, { 'rust create 201': (r) => r.status === 201 });
    if (res.status === 201) {
      rustTodoId = res.json('id');
    }
  });

  if (rustTodoId) {
    group('read via Go & Spring (rust todo)', () => {
      const goRes = http.get(`${goBase}/api/v1/todos/${rustTodoId}`);
      const springRes = http.get(`${springBase}/api/v1/todos/${rustTodoId}`);
      check(goRes, { 'go GET 200 (rust todo)': (r) => r.status === 200 });
      check(springRes, { 'spring GET 200 (rust todo)': (r) => r.status === 200 });
    });

    group('update via Rust', () => {
      const res = http.put(
        `${rustBase}/api/v1/todos/${rustTodoId}`,
        JSON.stringify({ title: `k6 rust updated ${suffix}`, completed: true }),
        jsonHeaders(),
      );
      check(res, { 'rust PUT 200': (r) => r.status === 200 });
    });

    group('delete via Go (rust todo)', () => {
      const res = http.del(`${goBase}/api/v1/todos/${rustTodoId}`);
      check(res, { 'go DELETE 204 (rust todo)': (r) => r.status === 204 });
    });
  }

  sleep(1);
}
