FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
ENV PORT=8081
COPY target/*-runner /work/application
EXPOSE 8081
USER 1001
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=${PORT}"]
